services:
  db:
    image: postgres:16
    container_name: ritmofit_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ritmofit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ritmofit_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ritmofit"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  ritmofit_pgdata:
